name:                branch-and-prune
version:             0.1.0.0
github:              "githubuser/branch-and-prune"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2024 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/branch-and-prune#readme>

dependencies:
- base >= 4.7 && < 5
# - row-types
- containers
- monad-logger
- text
- unliftio-core
- mixed-types-num
- aern2-mp

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  branch-and-prune-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - branch-and-prune

tests:
  branch-and-prune-test:
    defaults: hspec/hspec@main
    dependencies:
    - hspec
    - branch-and-prune
